sylius_resource:
  resources:
    sylius_mollie_plugin.onboarding_wizard_status:
      driver: doctrine/orm
      classes:
        model: Sylius\MolliePlugin\Entity\OnboardingWizardStatus
        interface: Sylius\MolliePlugin\Entity\OnboardingWizardStatusInterface
