sylius_resource:
    resources:
        sylius_mollie_plugin.product_type:
            driver: doctrine/orm
            classes:
                model: Sylius\MolliePlugin\Entity\ProductType
                interface: Sylius\MolliePlugin\Entity\ProductTypeInterface
                form: Sylius\MolliePlugin\Form\Type\ProductTypeType
