sylius_grid:
    grids:
        sylius_mollie_plugin_template_mollie_email:
            driver:
                name: doctrine/orm
                options:
                    class: Sylius\MolliePlugin\Entity\TemplateMollieEmail
            fields:
                name:
                    type: string
                    label: sylius_mollie_plugin.ui.template_name
                subject:
                    type: string
                    label: sylius_mollie_plugin.ui.template_subject
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
            filters:
                name:
                    type: string
                    label: sylius_mollie_plugin.ui.search
                subject:
                    type: string
                    label: sylius_mollie_plugin.ui.level
