sylius_twig_hooks:
    hooks:
        'sylius_mollie.admin.product_type.create.content.header':
            breadcrumbs:
                template: '@SyliusMolliePlugin/admin/product_type/create/content/header/breadcrumbs.html.twig'
