mollie_admin_shipment_split:
  path: /orders/{orderId}/shipments/{id}/split/
  methods: [GET, POST]
  defaults:
    _controller: sylius.controller.shipment::createAction
    _sylius:
      factory:
        method: [expr:service('sylius_mollie_plugin.factory.shipment_factory'), createWithOrderInventorySourceAndMethodFromShipment]
        arguments: [expr:notFoundOnNull(service('sylius.repository.shipment').find($id))]
      flash: sylius_mollie_plugin.admin.shipment.successfuly_split_and_sent
      form:
        type: Sylius\MolliePlugin\Form\Type\PartialShip\PartialShipType
        options:
          shipment: expr:notFoundOnNull(service('sylius.repository.shipment').find($id))
      permission: true
      redirect:
        route: sylius_admin_order_show
        parameters: { id: $orderId }
      section: admin
      state_machine:
        graph: sylius_shipment
        transition: create_and_ship
      template: '@SyliusMolliePlugin/Admin/PartialShip/shipmentSplit.html.twig'
      vars:
        header: sylius_mollie_plugin.ui.splitting_shipment_for_order
        icon: boxes
        route:
          name: mollie_admin_shipment_split
          parameters:
            id: $id
            orderId: $orderId
        templates:
          header_title: '@SyliusMolliePlugin/Admin/PartialShip/_headerTitle.html.twig'
          breadcrumb: '@SyliusMolliePlugin/Admin/PartialShip/_breadcrumb.html.twig'
