name: Build and publish

on:
    workflow_dispatch: ~
#    push:
#        branches:
#            - '**'
#        tags:
#            - 'v*.*.*'
#    pull_request:
#        branches:
#            - 'master'
#    release:
#        types: [ created ]
#    schedule:
#        -   cron: "0 1 * * 6" # Run at 1am every Saturday
#
jobs:
    build_and_publish:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

#            -   name: Declare GIT variables
#                id: vars
#                shell: bash
#                run: |
#                    echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | awk '{print tolower($0)}')"
#                    echo "##[set-output name=repository;]$(echo ${{ github.event.repository.name }} | awk '{print tolower($0)}')"
#                    echo "##[set-output name=registry_repository;]$(echo ${{ github.event.repository.name }} |sed -e 's/\([A-Z]\)/-\L\1/g' -e 's/^-//')"
#                    echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
#            -
#                name: Docker meta
#                id: meta
#                uses: docker/metadata-action@v3
#                with:
#                    images: |
#                        ${{ secrets.DOCKER_REPOSITORY_HOSTNAME }}/${{ steps.vars.outputs.registry_repository }}
#                    tags: |
#                        type=schedule
#                        type=ref,event=branch
#                        type=ref,event=pr
#                        type=semver,pattern={{version}}
#                        type=semver,pattern={{major}}.{{minor}}
#                        type=semver,pattern={{major}}
#                        type=sha
#
#            -   name: Docker Login
#                uses: docker/login-action@v1.10.0
#                if: github.event_name != 'pull_request'
#                with:
#                    registry: registry.mollie.shop
#                    username: ${{ secrets.DOCKER_REPOSITORY_LOGIN }}
#                    password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
#                    logout: true
#
#            -   name: Build and push php
#                uses: docker/build-push-action@v2
#                if: github.event_name != 'pull_request'
#                with:
#                    context: .
#                    target: result_php
#                    push: ${{ github.event_name != 'pull_request' }}
#                    tags: ${{ steps.meta.outputs.tags }}
#                    labels: ${{ steps.meta.outputs.labels }}
